version: "3"
services:
  node1:
    build: .
    container_name: node1
    hostname: node1
    networks:
      mpi-net:
        aliases:
          - node1

  node2:
    build: .
    container_name: node2
    hostname: node2
    networks:
      mpi-net:
        aliases:
          - node2

  node3:
    build: .
    container_name: node3
    hostname: node3
    networks:
      mpi-net:
        aliases:
          - node3

  node4:
    build: .
    container_name: node4
    hostname: node4
    networks:
      mpi-net:
        aliases:
          - node4
networks:
  mpi-net:
    driver: bridge
